### ISSUE TITLE
About transaction availability

### ISSUE THREAD

**Issue by realLiangshiwei** [Mongo2Go/Mongo2Go#100]
Mongo2Go is a great library, but we found some problems when using.

The [document](https://github.com/Mongo2Go/Mongo2Go#single-server-replica-set-mode-to-enable-transactions) explains to use single server replica set mode to enable transactions, but after testing I think it is invalid.

Test code is very simple：

```csharp
var runner = MongoDbRunner.Start(singleNodeReplSet: true, singleNodeReplSetWaitTimeout: 65535); // max timeout value

var client = new MongoClient(runner.ConnectionString);

using (var session = client.StartSession())
{
    session.StartTransaction();
}
```
The result:

![image](https://user-images.githubusercontent.com/16813853/92597340-d72b8500-f2d9-11ea-9796-c8bf44a58e0e.png)

I see that you use the `transition to primary complete; database writes are now permitted` message to determine whether the transaction is available, but this is not enough.

https://github.com/Mongo2Go/Mongo2Go/blob/958b052a94b54b1cbe2f464c065bc2abdf87f9f5/src/Mongo2Go/Helper/MongoDbProcessStarter.cs#L50

This is the code for mongo driver to determine whether the transaction is available

https://github.com/mongodb/mongo-csharp-driver/blob/44fff3f7d618ade5eed7a3e874407ecbc231997c/src/MongoDB.Driver.Core/Core/Bindings/CoreSession.cs#L461

I think we can use the same logic

``` csharp
// wait until transaction is ready or until the timeout is reached
SpinWait.SpinUntil(() => client.Cluster.Description.Servers.Where(s => s.State == ServerState.Connected && s.IsDataBearing).Any(), TimeSpan.FromSeconds(singleNodeReplSetWaitTimeout));
```

Now, it works:

![image](https://user-images.githubusercontent.com/16813853/92598221-19a19180-f2db-11ea-8604-d6318a9f8d35.png)

What do you thank?

**Comment by JohannesHoppe** [comment]
👍

**Comment by JohannesHoppe** [comment]
New version released. Please try out Mongo2Go 2.2.13.
