### ISSUE TITLE
Question: issue with 2.2.13 nuget package? 

### ISSUE THREAD

**Issue by zmira** [Mongo2Go/Mongo2Go#102]
Hi.

Below are contents of the installed nuget packages for versions 2.2.12 and 2.2.13 of Mongo2Go. While **2.2.12** has `dll`, `pdb`, and `deps.json`, for version **2.2.13** only `_._` is present... possible issue with the nuget package?

![image](https://user-images.githubusercontent.com/3380982/96429965-76a53700-11f9-11eb-8ff4-70ac8179bda1.png)

**Comment by JohannesHoppe** [comment]
Issue confirmed!
![Uploading Screen Shot 2020-10-19 at 13.05.18.png…]()

**Comment by JohannesHoppe** [comment]
I'm going to replace v2.2.13 with v2.2.14 and mark the broken one as obsolete on NuGet,
