### ISSUE TITLE
Could not find a part of the path 'D:\packages' when runner.Start() is activated

### ISSUE THREAD

**Issue by programmingworld1** [Mongo2Go/Mongo2Go#104]
Hi,

In my code I make use of mongo2go to write some integration tests, but I get the following error: "Could not find a part of the path 'D:\packages'"

I have been struggling to fix this problem, can someone please help me out with this one? 

PS: I make use of Visual Studio, the project under test is based on ASP.NET Core 3.1, the tests are written using xUnit.

The code for using mongoto is as follows:

`    public class RepositoryTests : IDisposable
    {
        protected IMongoDbContext dbContext;
        private MongoDbRunner _runner;

        public RepositoryTests(string coll)
        {
            _runner = MongoDbRunner.Start();

            Mock<ILogger<MongoDbContext>> loggerMock = new Mock<ILogger<MongoDbContext>>();

            MongoDbOptions mongoOpts = new MongoDbOptions
            {
                DefaultCollectionName = coll,
                ConnectionString = _runner.ConnectionString,
                DatabaseName = "IntegrationTest"
            };

            dbContext = new MongoDbContext(loggerMock.Object, Microsoft.Extensions.Options.Options.Create(mongoOpts));
        }

        public void Dispose()
        {
            _runner.Dispose();
        }
    }`  

complete error:
Message: 
    System.IO.DirectoryNotFoundException : Could not find a part of the path 'D:\packages'.
  Stack Trace: 
    FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
    FileSystemEnumerator`1.Init()
    FileSystemEnumerator`1.ctor(String directory, Boolean isNormalized, EnumerationOptions options)
    FileSystemEnumerable`1.ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
    FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
    Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
    FolderSearch.FindFolder(String startPath, String searchPattern)
    FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
    FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
    FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
    FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
    FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
    FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
    FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
    FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
    MongoBinaryLocator.FindBinariesDirectory(IList`1 searchDirectories)
    MongoBinaryLocator.ResolveBinariesDirectory()
    MongoBinaryLocator.get_Directory()
    MongoDbRunner.ctor(IPortPool portPool, IFileSystem fileSystem, IMongoDbProcessStarter processStarter, IMongoBinaryLocator mongoBin, String dataDirectory, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout)
    MongoDbRunner.Start(String dataDirectory, String binariesSearchPatternOverride, String binariesSearchDirectory, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout)
    RepositoryTests.ctor(String coll) line 20
    ResumeRepositoryTests.ctor() line 17

**Comment by JohannesHoppe** [comment]
And how did you solved the problem?

**Comment by programmingworld1** [comment]
> And how did you solved the problem?

I did not solve this issue, I accidently opened two isues, because of that I closed this one.
