### ISSUE TITLE
Could not find a part of the path 'D:\packages

### ISSUE THREAD

**Issue by programmingworld1** [Mongo2Go/Mongo2Go#105]
Hi,

In my code I make use of mongo2go to write some integration tests, but I get the following error: "Could not find a part of the path 'D:\packages'"

I have been struggling to fix this problem, can someone please help me out with this one? 

PS: I make use of Visual Studio, the project under test is based on ASP.NET Core 3.1, the tests are written using xUnit and I have a windows 10 OS computer where it runs on. It works on Linux though (when I deploy it to a linux env, it works).. so I think there is something wrong with environment/env-variables that is should create?

The code for using mongoto is as follows:

`    public class RepositoryTests : IDisposable
    {
        protected IMongoDbContext dbContext;
        private MongoDbRunner _runner;

        public RepositoryTests(string coll)
        {
            _runner = MongoDbRunner.Start();

            Mock<ILogger<MongoDbContext>> loggerMock = new Mock<ILogger<MongoDbContext>>();

            MongoDbOptions mongoOpts = new MongoDbOptions
            {
                DefaultCollectionName = coll,
                ConnectionString = _runner.ConnectionString,
                DatabaseName = "IntegrationTest"
            };

            dbContext = new MongoDbContext(loggerMock.Object, Microsoft.Extensions.Options.Options.Create(mongoOpts));
        }

        public void Dispose()
        {
            _runner.Dispose();
        }
    }`  

complete error:
Message: 
    System.IO.DirectoryNotFoundException : Could not find a part of the path 'D:\packages'.
  Stack Trace: 
    FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
    FileSystemEnumerator`1.Init()
    FileSystemEnumerator`1.ctor(String directory, Boolean isNormalized, EnumerationOptions options)
    FileSystemEnumerable`1.ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
    FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
    Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
    FolderSearch.FindFolder(String startPath, String searchPattern)
    FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
    FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
    FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
    FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
    FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
    FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
    FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
    FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
    MongoBinaryLocator.FindBinariesDirectory(IList`1 searchDirectories)
    MongoBinaryLocator.ResolveBinariesDirectory()
    MongoBinaryLocator.get_Directory()
    MongoDbRunner.ctor(IPortPool portPool, IFileSystem fileSystem, IMongoDbProcessStarter processStarter, IMongoBinaryLocator mongoBin, String dataDirectory, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout)
    MongoDbRunner.Start(String dataDirectory, String binariesSearchPatternOverride, String binariesSearchDirectory, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout)
    RepositoryTests.ctor(String coll) line 20
    ResumeRepositoryTests.ctor() line 17

**Comment by programmingworld1** [comment]
Can someone please explain how this can be solved and why this error happens?

**Comment by kenoma** [comment]
It looks like path to nuget cache is hardcoded to `%USERPROFILE%\\.nuget\\packages`, so, if you have moved your user folders to another place you'll receive this error.

**Comment by JohannesHoppe** [comment]
PR welcome here! 🙂

**Comment by kenoma** [comment]
https://github.com/Mongo2Go/Mongo2Go/pull/107

**Comment by JohannesHoppe** [comment]
fixed by #107 in v2.2.16

**Comment by JohannesHoppe** [comment]
@programmingworld1 please report if this fix works for you. If not, please report! 👍
