### ISSUE TITLE
Creating collections (and views) in transaction

### ISSUE THREAD

**Issue by TonyTroeff** [Mongo2Go/Mongo2Go#112]
Since Mongo DB v4.4 we can create collections (respectively views) within multi-document transactions.
https://docs.mongodb.com/manual/core/transactions/#create-collections-and-indexes-in-a-transaction

However, this does not work with Mongo2Go and I would really appreciate it if this could be implemented.

**Comment by JohannesHoppe** [comment]
should be fixed in v3.0.0 via #109, please re-open this issue if the new release still does not support your requirement
