### ISSUE TITLE
Configure logging

### ISSUE THREAD

**Issue by corentinaltepe** [Mongo2Go/Mongo2Go#113]
Thank you so much for this excellent tool!

My understanding right now is that mongo2go outputs its logs to the console, without possibility to configure them. I also noticed the structure of the logs has changed with v3 (more readable and parsable). Would there be a way to configure the logging generated by the tool? The logs generate a lot of noise in CI output.

I know I could turn the output off by calling `MongoDbRunner.Start(additionalMongodArguments: "--quiet");`, but would there be any way to inject a logger (ideally, a `Microsoft.Extensions.Logging.Abstraction.ILogger`) or [configure it with a builder](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerfactory.create?view=dotnet-plat-ext-5.0) (`Action<ILoggingBuilder>`), so that to pipe the logs to something completely customized to our use?

**Comment by JohannesHoppe** [comment]
I absolutely agree with you that this feature would be very useful. However, I don't have the resources to implement it. Therefore, I invite you to do so. I would definitely merge such a PR! 🙂 👍

**Comment by JohannesHoppe** [comment]
see also #94

**Comment by corentinaltepe** [comment]
Thank you for your response. I'd like to at least give it a try. I'm unfamiliar with the code base. Would you have any pointers where to start?

I'm guessing:
1. Provide options in `Start()` signature.
2. Find where mongodb logs are wired to the console.
3. Work the magic in between.
