### ISSUE TITLE
Last release broke for Net 5.0

### ISSUE THREAD

**Issue by Anapher** [Mongo2Go/Mongo2Go#120]
Hey,
I'm using Mongo2Go in a .Net 5.0 project. Version 3.1.1 is working totally fine, but version 3.1.2 doesn't find any libraries to reference, so the classes from Mongo2Go aren't available and my project does not compile. Maybe it has something to do with the change to .Net Standard 2.0?

**Comment by JohannesHoppe** [comment]
Do you have an error message?

@0xced what do you think?! 🤔

**Comment by Anapher** [comment]
No, but it's very easy to reproduce: Create a new .Net 5.0 project, add mongo2go, try to use it. There is no error message, there is just no reference to the mongo2go library so you can not use MongoDbRunner.

**Comment by 0xced** [comment]
I think it's a NuGet packaging issue. There's an empty `netstandard2.1` directory in the 3.1.2 release and I think it might be the root cause of this issue. I have opened #121 which should help you create a clean NuGet release.

**Comment by JohannesHoppe** [comment]
Obviously I forgot to delete the empty folder before building. Fortunately, this should not happen again with the new build per #121. 👍 
I will publish a new version this evening.

**Comment by 0xced** [comment]
Mongo2Go version [3.1.3 is up on NuGet](https://www.nuget.org/packages/Mongo2Go/3.1.3) and works fine, even on .NET Framework now. 🎉

**Comment by JohannesHoppe** [comment]
# 🎉
