### ISSUE TITLE
Continuous integration (GitHub Actions)

### ISSUE THREAD

**Issue by JohannesHoppe** [Mongo2Go/Mongo2Go#122]
Next step is considering building and publishing the package on a continuous integration system such as GitHub Actions. 😉
You can take inspiration from my [continuous-integration.yml](https://github.com/0xced/serilog-formatting-log4net/blob/main/.github/workflows/continuous-integration.yml) if you want. Don't hesitate to ask if you have questions.

_Originally posted by @0xced in https://github.com/Mongo2Go/Mongo2Go/issues/121#issuecomment-829711473_

**Comment by JohannesHoppe** [comment]
@0xced Welcome to our awesome team of two! 😄 👍

**Comment by 0xced** [comment]
I tried something, let's see what happens…

https://github.com/Mongo2Go/Mongo2Go/actions/runs/799229125

**Comment by 0xced** [comment]
All ✅ on first try. 🎉
