### ISSUE TITLE
Changing the default nuget cache folder breaks binary search

### ISSUE THREAD

**Issue by matthias-barann** [Mongo2Go/Mongo2Go#126]
Hello,

I have a problem using the MongoDbRunner if using a non-default nuget package location:

`Class Initialization method Thermo.Discoverer.ServiceCaseManagement.WebApi.UnitTests.TestWebApi.ClassInitialize threw exception. Mongo2Go.MonogDbBinariesNotFoundException: Mongo2Go.MonogDbBinariesNotFoundException: Could not find Mongo binaries using the search patterns "tools\mongodb-win32*\bin", "packages\Mongo2Go*\tools\mongodb-win32*\bin", and "packages\mongo2go\*\tools\mongodb-win32*\bin".  You can override the search pattern and directory when calling MongoDbRunner.Start.  We have detected the OS as Microsoft Windows 10.0.18363.`

In `src/Mongo2Go/Helper/MongoBinaryLocator.cs` you specify the nuget cache folder as:

`public const string WindowsNugetCacheLocation = @"%USERPROFILE%\.nuget\packages";`

However, the nuget cache location can be altered on the system by setting the `NUGET_PACKAGES` env variable [(see here)](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders).
As a consequence, binaries will not be found if NUGET_PACKAGES is specified.

I know I can specify the binary directory in MongoDbRunner.Start, and that allows me to run the unit tests. However, it makes the code non-shareable with other colleagues.

I would suggest that the search for binaries also tries to look into %NUGET_PACKAGES% if it could not find a match in %USERPROFILE%.

**Comment by JohannesHoppe** [comment]
But we have support for the `NUGET_PACKAGES` env variable?!

see here https://github.com/Mongo2Go/Mongo2Go/blob/9b82f6cab8282135f95394bf4dcdea296f9cf125/src/Mongo2Go/Helper/MongoBinaryLocator.cs#L28

Doesn't it work as required? 🤔

**Comment by matthias-barann** [comment]
Oh, overlooked that.
That's curious then. I have the following env variable defined:

![image](https://user-images.githubusercontent.com/43539584/125746975-22268de8-916d-4cb9-828b-e1058472afdf.png)

When I run MongoDbRunner.Start without specifying the "binariesSearchDirectory" it tries to find the binaries in these locations:

```
We walked up to root directory from the following locations.
     <project-dir>\bin\x64\Debug\net5.0
    C:\Users\<xxx>\.nuget\packages.
```

However, if I specify the full path to the package:
`binariesSearchDirectory: @"D:\\Nuget\\packages\\mongo2go\\2.2.16"`
it works fine.

Just for reference, I am using:
`<PackageReference Include="Mongo2Go" Version="2.2.16" />`

**Comment by matthias-barann** [comment]
It might also be worth mentioning, that the env variable must be available to Visual Studio, else it would not have downloaded the package to the D:\ location.

**Comment by matthias-barann** [comment]
Just to be very sure about it, I wrote the env variable to the console before using the MongoDbRunner:

```
Console.WriteLine(Environment.GetEnvironmentVariable("NUGET_PACKAGES"));
m_mongoDbRunner = MongoDbRunner.Start(singleNodeReplSet: true)
```

This gives me: `D:\Nuget\packages`

**Comment by JohannesHoppe** [comment]
Ok, that's the problem. Support for `NUGET_PACKAGES ` was introduced in Mongo2Go 3.0.0, March 26 2021. This is one of more breaking changed that required us the introduce the new major version 3.
