### ISSUE TITLE
SingleNodeReplSet hangs during the Azure's pipeline's tests

### ISSUE THREAD

**Issue by Sebex0** [Mongo2Go/Mongo2Go#129]
Hi!

I was using Mongo2Go successfully for a couple of months. We have used it in the integration tests project for a .NET 5 solution. The project with tests is configured to be run on each automated CI/CD process. Mongo2Go is configured to run as a single node replica set as we want to use the transactions.

Everything was working just fine untill last week. Noone changed anything and suddenly the pipelines started to occasionally hang. They do not fail, they do not even proceed, the whole process of tests does nothing and after the default 1 hour the whole pipeline fails. There is no strict way to reproduce our problem, the only one thing I can find in the logs, that differs a successfull and unsuccessfull try, are the lines connected to sessions caching

```
{"t":{"$date":"2021-09-21T07:40:35.611+00:00"},"s":"I",  "c":"STORAGE",  "id":20320,   "ctx":"LogicalSessionCacheRefresh","msg":"createCollection","attr":{"namespace":"config.system.sessions","uuidDisposition":"generated","uuid":{"uuid":{"$uuid":"6bdfa47c-dba0-4398-ad98-bc58ecf83051"}},"options":{}}}
{"t":{"$date":"2021-09-21T07:40:35.612+00:00"},"s":"I",  "c":"CONTROL",  "id":20712,   "ctx":"LogicalSessionCacheReap","msg":"Sessions collection is not set up; waiting until next sessions reap interval","attr":{"error":"NamespaceNotFound: config.system.sessions does not exist"}}
{"t":{"$date":"2021-09-21T07:40:35.637+00:00"},"s":"I",  "c":"INDEX",    "id":20345,   "ctx":"LogicalSessionCacheRefresh","msg":"Index build: done building","attr":{"buildUUID":null,"namespace":"config.system.sessions","index":"_id_","commitTimestamp":{"$timestamp":{"t":1632210035,"i":2}}}}
{"t":{"$date":"2021-09-21T07:40:35.637+00:00"},"s":"I",  "c":"INDEX",    "id":20345,   "ctx":"LogicalSessionCacheRefresh","msg":"Index build: done building","attr":{"buildUUID":null,"namespace":"config.system.sessions","index":"lsidTTLIndex","commitTimestamp":{"$timestamp":{"t":1632210035,"i":2}}}}
```

Do you have any suggestions what and how to configure to prevent such problems? I can add, that the problems happen in like 60-75% of attempts. The exact same version of code one time ends without any problems and the very next time hangs...

**Comment by JohannesHoppe** [comment]
I'm sorry, I can't help on that because a) I'm not that active in .NET world anymore and b) I do not own an DevOps instance.

I would recommend that you compile Mongo2Go on your own and that you try to figure out via Logging (or Debugging?) what's going wrong. I'm happy to merge any PR! 👍

**Comment by Sebex0** [comment]
Hi!

Thank you for the response, it seems I just overreacted - all my initial logs suggested the problem is connected strictly to Mongo2Go. It was not. Even without it - still some problems, so it wasn't it :)
