### ISSUE TITLE
Alternative to Mongo2Go

### ISSUE THREAD

**Issue by asimmon** [Mongo2Go/Mongo2Go#142]
I discovered this project a few months ago, and I used it in several projects at work.  Thank you @JohannesHoppe, @0xced  and all the other contributors for creating and maintaining it.

However, I had several issues, some of them are already opened:

* Lack of support for newer MongoDB versions,
* Issues with binaries path resolving,
* Package size concern,
* Binaries are versioned, which leads to security, scaling and versioning concerns,
* Stdout, stderr and logging could be improved,
* Process handling could be improved.

At first I tried to contribute to the project, but there would have been too many breaking changes. Other things such as the versioning, or multiple packages would have not been easy to change too.

I ended up starting from a clean slate to prevent any limitation: https://github.com/asimmon/ephemeral-mongo

* Support for multiple major MongoDB versions that are copied to the build output,
* There is a separate NuGet package for each operating system and MongoDB version so it's easier to support new major versions,
* The latest MongoDB binaries are safely downloaded and verified by GitHub actions during the build or release workflow, reducing the Git repository size,
* There's less chances of memory, files and directory leaks. The startup is faster by using C# threading primitives such as `ManualResetEventSlim`.
* The CI tests the generated packages against .NET 4.6.2, .NET Core 3.1 and .NET 6 using the latest GitHub build agents for Ubuntu, macOS and Windows.

Would you consider proposing https://github.com/asimmon/ephemeral-mongo as an alternative? This could solve many issues encountered by the community.

**Comment by JohannesHoppe** [comment]
# :+1:

You are absolutely right. Maintaining old open source projects is a burden. If you send a pull request for the README, I will merge it. You could write that there is a suitable feature-rich alternative and that your tool can be a replacement. No more than 5 sentences, please. Mongo2Go is not dead, but is also no longer actively developed.

**Comment by asimmon** [comment]
Thank you @JohannesHoppe, I just opened the a the PR #143
