### ISSUE TITLE
MongoCommandException thrown when setting the SeverApi in MongoClientSettings

### ISSUE THREAD

**Issue by alexanderslagle** [Mongo2Go/Mongo2Go#145]
We set up the API settings (API settings in [ Mongo's documentation](https://www.mongodb.com/docs/drivers/csharp/#stable-api)), and FindAsync() fails in our Unit Test.

![API Settings](https://user-images.githubusercontent.com/47549280/212730383-52a44707-a250-46b9-996c-46a93ea47dec.png)

![Exception](https://user-images.githubusercontent.com/47549280/212730377-d6afa349-5f69-464f-adc2-8e3420088c9b.png)

**Comment by asimmon** [comment]
https://www.mongodb.com/docs/drivers/csharp/current/fundamentals/stable-api/#enable-the-stable-api-on-a-mongodb-client

![image](https://user-images.githubusercontent.com/14242083/223899734-a166fa7d-a81e-46f0-a481-03fbb3833310.png)

**Comment by JohannesHoppe** [comment]
Mongo2Go uses right now MongoDB 4. I might update it soonish.
