### ISSUE TITLE
process and data not cleaning up when I stop a test

### ISSUE THREAD

**Issue by cottsak** [Mongo2Go/Mongo2Go#17]
So I'm running my tests in the R# runner and debugging locally. Before my `using` block completes I'm stopping the test which AFAIK should call the finaliser on the `MongoDbRunner` instance. Only, I suspect that, we're not getting past this line https://github.com/JohannesHoppe/Mongo2Go/blob/master/src/Mongo2Go/MongoDbRunner.IDisposable.cs#L28 and we should be. The result is that my process stays alive when it should terminate and my data folder is not cleaned up.

If this can be resolved, then perhaps https://github.com/JohannesHoppe/Mongo2Go/issues/16 is moot.

**Comment by cottsak** [comment]
Maybe your `if (State != State.Running) return;` logic should be inside the `if (disposing)` block below it?

**Comment by JohannesHoppe** [comment]
You are right, the plan is that every process is killed in the end. Stuff like this is hard to debug, for sure.
I'm open for any PR, since I have to time to fix that in a reasonable time.

**Comment by cottsak** [comment]
I don't mind making a PR but can you push an update to the nuget package easily?

**Comment by JohannesHoppe** [comment]
Every time. It’s "my" package. :smile: 
Please try to reproduce the issue with a new test – if possible.

**Comment by G3N7** [comment]
This is a problem I run into as well, when you submit the pull request I will also try and verify the fix.

**Comment by G3N7** [comment]
I have attempted to make this change locally, and see no change in behavior.  What are you basing the statement about the finalizer behavior on?

If I remove all guards and make the logic:
```csharp
private void Dispose(bool disposing)
{
    _mongoDbProcess.Dispose();

    _fileSystem.DeleteFolder(_dataDirectoryWithPort);
            
    Disposed = true;
    State = State.Stopped;
}
```
I'm not sure how the runner behaves but this does not look to be a fix for that behavior.  Until the console window is closed the runner does not appear to shut down regardless of if I stop debugging or stop execution in ReSharper.

**Comment by cottsak** [comment]
Gimme a shot.. I've come to a point where this is worth my time. :p

**Comment by G3N7** [comment]
Sounds great, please reach out if you could use any help or have any questions.

**Comment by cottsak** [comment]
I'm not having any luck.

I'm testing the scenario where execution doesn't reach the end of a `using` block so that the `Dispose()` method is called. But that's not a problem right? Because that's what `~MongoDbRunner()` is for right? Well yes, only it's not being called AFAIK (and this is *really* hard to test/debug). 

I've inserted logging to disk since I can't trust the debugger/output when asking the test to terminate and I've verified that the Finalizer is not being called when the test is stopped with the R# runner (**Stop Execution** and **Stop Execution** `--force`). 

I'm not sure what to do. Maybe I just have to live with this? :cry:

**Comment by cottsak** [comment]
I thought I was going crazy expecting a test runner to call `Dispose()` or at least Finalise objects inside the scope of a terminated test..

Turns out this is not limited to the Resharper Test Runner. I reproduced the same behaviour using the xunit plugin for the VS Runner (`xunit.runner.visualstudio`). I also know it's not xunit because when I loaded this repo I installed https://github.com/machine/machine.specifications.runner.resharper and I have the problem in the source too. 

I wish there was someone at Jetbrains (@citizenmatt, anyone?) who could explain to me what's going on here.

**Comment by JohannesHoppe** [comment]
I guess the problem still exists.
PR #18 only gives isolated folders, but it's still not cleaned up, right?

**Comment by cottsak** [comment]
Correct. https://github.com/JohannesHoppe/Mongo2Go/pull/18 isolates the data for repeat runs in the same location. The process is still not "dying" properly. 

I don't know why the runners aren't calling the finalizer. Maybe I just don't understand how they
re supposed to work.

NCrunch seems to clean the processes up better but I know from experience that it's thanks to NCrunch's additional test host that this is possible.

This whole thing is kinda bringing all I thought I knew about `Dispose()` and cleaning up unmanaged processes into question.. which for learning sake is probably good. But it's still frustrating.

**Comment by cottsak** [comment]
Wild idea: Is there some common interface that test helpers should implement which is a convention that most/all test runners observe such that my helper can be directed to clean-up/die/Dispose when a forced termination invoke is made? 
My gut just screams: duh! it's `IDisposable` but obviously this isn't working based on [what I thought I knew about how Dispose should work](https://lostechies.com/chrispatterson/2012/11/29/idisposable-done-right/).

**Comment by bradwilson** [comment]
Finalizers are called by the CLR, not by any individual library. There is no _guarantee_ that they will be called, though. http://stackoverflow.com/a/3458203

`IDisposable`, on the other hand, is definitely the responsibility of user code, not the system itself. Is there some scenario in which you believe @xunit is not cleaning things up?

**Comment by cottsak** [comment]
Thanks @bradwilson.

It's hard to say whether @xunit should be responsible ever. For xunit to dispose my test (which then should dispose the runner, which then should kill the process), the runner should end the test when I use the force command provided by R#. I don't know what is failing at what point but I'm not seeing it cleaned up.

Interestingly, when I try to use the R# runner without the [disabling of parallelization](https://github.com/JohannesHoppe/Mongo2Go/issues/19), and I get two processes launched (and hanging) at the same time, the terminate command from R# presents a dialog asking me if I want to confirm the termination of the two tracked processes. Weird! So if it can track two, why can't track one?

**Comment by citizenmatt** [comment]
Can you give a bit more context, please? I'm not sure what you're trying to achieve when stopping the ReSharper runner.

Some background on what ReSharper does: when you first click stop in R#, it does a "cooperative" stop - it lets the current test(s) complete, the stops the run, using the standard xunit API. This should do all the normal clean up that xunit will do - dispose test classes and fixtures, etc. But this doesn't help with a hang, though, so if you hit it again, it kills the process, and there is no chance to do cleanup. R# will look for any child processes, and ask you if you want to kill those, too.

**Comment by cottsak** [comment]
@citizenmatt I'm trying to get R# to kill the process. I'm essentially wanting the R# stop command to get to this line https://github.com/JohannesHoppe/Mongo2Go/blob/master/src/Mongo2Go/MongoDbRunner.IDisposable.cs#L40

When the test is allowed to complete (ie, reach the end of the `using` block) then the normal `Dispose` behaviour seems to take place. We reach https://github.com/JohannesHoppe/Mongo2Go/blob/master/src/Mongo2Go/MongoDbRunner.IDisposable.cs#L40 and the process goes away. Even when exceptions happen - exception triggers the end of `using` scope and `Dispose()` is called.

However, when I'm debugging and I detach the debugger, or when something else in my test prevents the completion of the test, the mongo process appears to hang. What does 'hang' mean? I don't know. It just doesn't terminate. But that's fine, because I expect to be able to kill it with the R# stop command. Only that doesn't work. And it [seems to be inconsistent](https://github.com/JohannesHoppe/Mongo2Go/issues/17#issuecomment-241206947) too. I can kill the process tho, I hit the little [x] on the console window. But I shouldn't have to.

Does that help?

**Comment by citizenmatt** [comment]
Clicking the stop button once should do what you're after. ReSharper signals the runner to finish, and it waits for the current test(s) to complete and then tells the xunit API to not run any more tests. So, once the test completes, the normal clean up should happen and your processes should be stopped - because of your `Dispose` code.

If you hit the stop button twice, though, ReSharper will kill the process that is running the tests. So your `Dispose` code doesn't get a chance to run. ReSharper makes a best effort at finding child processes. It does this by enumerating the processes in the system, and looking for any with a parent process ID matching the runner's. If it finds them, it will ask, and then abort the child processes too. One thing it doesn't do is abort grand-child processes and below, only direct children.

If you terminate the runner any other way, such as stopping the debugger, your `Dispose` code won't run, and ReSharper's abort process isn't called, so child processes aren't touched.

**Comment by JohannesHoppe** [comment]
Many thanks for this detailed explanation!

**Comment by cottsak** [comment]
@citizenmatt I understand what you're saying and from my guessing I would have arrived at the behaviour you describe. The version of R# I have is plain and simple not doing that.

I've upgraded to latest now so I'll come back here if I see this again. Thanks for help out @citizenmatt

**Comment by G3N7** [comment]
This seams safe to close, do you agree @JohannesHoppe

**Comment by JohannesHoppe** [comment]
I absolutely agree! We talked about this, and we are now all aware, that you should not interrupt a running test suite! 😉
