### ISSUE TITLE
Multiple processes don't seem to work in parallel

### ISSUE THREAD

**Issue by cottsak** [Mongo2Go/Mongo2Go#19]
I'm using `[assembly: CollectionBehavior(DisableTestParallelization = true)]` to ensure that my test processes don't run along side each other. When I remove this switch the processes hang (if there is more than one running at a time) and no tests complete.

I've tested this when running another mongod.exe process running (another local server) and with the `[assembly: CollectionBehavior(DisableTestParallelization = true)]` tests pass, without, they hang. So I know it's not about the total number of concurrent mongod.exe processes on the system.

If they're using different ports and different folders on disk, why the contention?

**Comment by JohannesHoppe** [comment]
Did you figured out something here?

**Comment by cottsak** [comment]
Still under investigation. I'm getting better results with NCrunch than the R# test runner, however I know that NCrunch has another layer of runner isolation (which gives it the ability to parallelise anything) verses [xunit's own parallel config](https://xunit.github.io/docs/running-tests-in-parallel.html) which the R# runner is respecting.

**Comment by JohannesHoppe** [comment]
I can't repeat this and the issue seems to be obsolete after one year... let's close it for now!
