### ISSUE TITLE
prevent windows firewall popup

### ISSUE THREAD

**Issue by cottsak** [Mongo2Go/Mongo2Go#21]
Can we prevent the Windows Firewall popup from appearing?

I'm getting it when I reset the test environment or restart VS, etc.

**Comment by JohannesHoppe** [comment]
I don't think so. That's a security feature of windows.

**Comment by JohannesHoppe** [comment]
As far as I know the only option is to disable the firewall...

**Comment by cottsak** [comment]
I think it's only presenting because the process opens a tcp listener. Is there a param you can pass to the process to prevent that? I mean, we don't need the tcp listener for in-memory work right?

**Comment by JohannesHoppe** [comment]
Sure. Clients communicate with the database server through a regular TCP/IP socket.
I'm not aware of any other protocoll.

see: https://docs.mongodb.com/manual/reference/mongodb-wire-protocol/

**Comment by cottsak** [comment]
So what we're saying is there's no avoiding the listener and so no avoiding the firewall warning? ☹️

**Comment by JohannesHoppe** [comment]
As far as I know – yes. My firewall is disabled…

**Comment by kubal5003** [comment]
We discovered this issue today too. I think I might have a solution - the window doesn't pop up when you pass the flag --bind_ip 127.0.0.1 to mongod.exe. 
Since Mongo2Go is intended for in process use I assume that this would be a safe change? If you agree I can prepare a PR.

**Comment by cottsak** [comment]
That sounds like a good idea. Safe assumption too I think.

**Comment by JohannesHoppe** [comment]
Yep. Localhost is fine.

Please keep in mind that #master is right now .NET Core only. If you want to target .NET 4.6.x I should make a branch first.

**Comment by JohannesHoppe** [comment]
.NET 4.6 - https://github.com/Mongo2Go/Mongo2Go/tree/dotNET_4.6
.NET Core 1.0 / .NET Standard 1.6 - https://github.com/Mongo2Go/Mongo2Go/tree/master

**Comment by kubal5003** [comment]
Thank you for creating a branch for the .NET 4.6 since we're using that version :) I'll try to update both of them.

**Comment by JohannesHoppe** [comment]
yay, cool! :+1: 

i think this would be a 1.1 and a 2.0.0-alpha2

**Comment by kubal5003** [comment]
I saw that you merged my PRs. How do we proceed ? What can I do now?

**Comment by JohannesHoppe** [comment]
I will bake two nuget packages today and upload them.
Then you could test! :-)

**Comment by kubal5003** [comment]
Thank you! We will update as soon as we get those :)

**Comment by JohannesHoppe** [comment]
Both NuGet packages are on nuget.org now.
Took me a little bit more time, since I had upgraded to VS 2017 (and removed old Visual Studio) ... :sweat_smile:  

### For .NET Framework 4.6.1

    Install-Package Mongo2Go -Version 1.1.0

### For .NET Standard 1.6

    Install-Package Mongo2Go -Version 2.1.0

**Comment by kubal5003** [comment]
I tested this today (1.1.0).  It works fine :) The firewall window does not appear. I also made sure to remove the firewall rule prior to testing. Do we want to test 2.1.0 before closing this?

**Comment by JohannesHoppe** [comment]
I think it's not necessary in this case!  Thanks for testing! :+1:
