### ISSUE TITLE
Updating to MongoDb Driver 2.3.0 / .NET 4.5

### ISSUE THREAD

**Issue by AlexZeitler** [Mongo2Go/Mongo2Go#22]
Would you accept a PR for MongoDb Driver 2.3.0 which also requires a .NET Version >= 4.5?

**Comment by JohannesHoppe** [comment]
This might break for some people. Is .NET >= 4.5 really required?

**Comment by AlexZeitler** [comment]
Looks like it as a dependency for the C# 2.x driver: https://docs.mongodb.com/ecosystem/drivers/csharp/#compatibility -> ".NET Language Compatibility"

**Comment by JohannesHoppe** [comment]
Allright.

@G3N7 @marcpiechura @cottsak @Silv3rcircl3 @onyxmaster @sweetlandj @krippz
... does somebody of you has complains / impediments about upgrading to .NET Version >= 4.5?
No replies counts as "no complains". ;-)

**Comment by cottsak** [comment]
Was using 4.6.1 here without runtime issues.

**Comment by onyxmaster** [comment]
No problem, we use 4.6.1 and 4.6.2 mixed environment.

**Comment by Silv3rcircl3** [comment]
No problem for me too.

**Comment by JohannesHoppe** [comment]
@AlexZeitler Go! :shipit:
