### ISSUE TITLE
Get a build working and shown in github as a canary

### ISSUE THREAD

**Issue by G3N7** [Mongo2Go/Mongo2Go#27]
I will start by using travis-ci and get things working there.

**Comment by JohannesHoppe** [comment]
I approved the Travis-CI access.

**Comment by G3N7** [comment]
Adding travis' hook to build requires admin for the repository @JohannesHoppe please enable the hook by going to https://travis-ci.org and click the little "+" on the left to "Add New Repostitory" and check the Mongo2Go repository to enable CI.

Once it builds on check-in, I will work on further automation.

**Comment by JohannesHoppe** [comment]
I already did?!

**Comment by JohannesHoppe** [comment]
https://travis-ci.org/Mongo2Go/Mongo2Go

**Comment by G3N7** [comment]
Thank you sir.

**Comment by JohannesHoppe** [comment]
Welcome Mr! :bowtie:

**Comment by JohannesHoppe** [comment]
Travis works like a charm (building and testing) via `dotnet text`...
