### ISSUE TITLE
Get a build working that targets legacy nuget configurations for 4.5 4.6

### ISSUE THREAD

**Issue by G3N7** [Mongo2Go/Mongo2Go#28]
I think we should try to model this after how Json.Net is making things work.

**Comment by JohannesHoppe** [comment]
:+1:

**Comment by G3N7** [comment]
I am going to start on this once I have automated the build, which should allow me to automate testing across the different targets.  Once we have strong test/automation we can let it do the publish upon passing check-in or pull request.

**Comment by JohannesHoppe** [comment]
a dream would come true! =)

**Comment by JohannesHoppe** [comment]
I'm going to ignore the old 1.x branch. Since .NET 4.7.1 it should be super easy to also consume .NET Standard packages. 
So we should be fine to simply test with `dotnet test`
