### ISSUE TITLE
Issues/Workarounds for VSTS Test Assemblies task

### ISSUE THREAD

**Issue by Mardoxx** [Mongo2Go/Mongo2Go#32]
I'm using VSTS with VS2017 hosted agent and had issue trying to get Mongo2Go to work. I restore my packages using MSBuild's restore.

- `MSBuild /t:restore` restores packages to `%USERPROFILE%/.nuget` by default, which is inaccessible from the directory searcher.
- Packages are stored in this folder under `{Name}\{Version}` [currently](https://github.com/Mongo2Go/Mongo2Go/blob/master/src/Mongo2Go/Helper/MongoBinaryLocator.cs#L9) it assumes `{Name}*{Version}*`

I worked around this by creating a copy files task with the following settings:

Source Folder: `$(USERPROFILE)\.nuget\packages\mongo2go\2.1.0\tools`
Contents: `**`
Target Folder: `$(System.DefaultWorkingDirectory)\tools`

Unsure what best course of action would be. Allowing an absolute path to packages would be one option? Or making it search `%USERPROFILE%/.nuget/packages` as well. That would perhaps be better?

**Comment by JohannesHoppe** [comment]
Thanks for reporting this!

Absolute paths would be not very generic. Is ` %USERPROFILE%` somewhere documented?
This new search-pattern belongs to the other search patterns.

**Comment by Mardoxx** [comment]
That's what I thought.

Apologies! %USERPROFILE% is a windows environment variable which expands to e.g. "C:/Users/{Username}". In VSTS Tasks you can reference env vars by using `$(Variable)` syntax. I think [this](https://technet.microsoft.com/en-us/library/dd560744(v=ws.10).aspx) is the official list?

I haven't been able to find official documentation on msbuild which says where the default directory for package restore is.  Nor can I find anything that says how to change it.

https://docs.microsoft.com/en-us/nuget/schema/msbuild-targets#restore-target seems to say you can add `<RestorePackagesPath>` to your `.csproj` file, but I could not get it to work.

Another thing to perhaps look in to is how msbuild determines where packages go on linux/osx. I can not test this as don't have appropriate environments set up -- and develop exclusively on windows at work.

**Comment by JohannesHoppe** [comment]
I can't repeat this. Works fine here and also runs fine on Travis. Please use the 2.x branch. With .NET 4.7.1 even legacy environments should be able to easily to consume .NET Standard packages nowadays. Please try the latest version of Mongo2Go and report if it works for you.
