### ISSUE TITLE
Add binaries for MongoDB 3.4

### ISSUE THREAD

**Issue by ash23** [Mongo2Go/Mongo2Go#34]
It would be great if we could be able to run MongoDB 3.4 (personally I need it since there are new Aggregation framework operators which I am using)

**Comment by JohannesHoppe** [comment]
Just make a PR! ;-)

* please care about binaries for all three platforms
* good enough: PR against `master` (i will cherry pick against `dotNET_4.6`) - or other way around
* please read https://github.com/Mongo2Go/Mongo2Go/issues/15 first

**Comment by JohannesHoppe** [comment]
A new version was pushed:  
Mongo2Go 2.2.0 contains binaries from MongoDB v3.4.7
... the 1.x branch is still on MongoDB v3.2.7
