### ISSUE TITLE
Support inMemory StorageEngine 

### ISSUE THREAD

**Issue by EtienneLorthoy** [Mongo2Go/Mongo2Go#36]
Hi !

It would be great if we could be able to run MongoDB with the option --storageEngine inMemory (https://docs.mongodb.com/manual/core/inmemory/) appended to the final cmd line. In order to achieve fastest tests !

Thanks !

**Comment by JohannesHoppe** [comment]
good idea, PR welcome

**Comment by JohannesHoppe** [comment]
This is a MongoDB Enterprise feature, and not available in the free version. I'm sorry! :-(

see: https://docs.mongodb.com/manual/core/inmemory/

**Comment by 3nuc** [comment]
It's possible to get this through `--storageEngine ephemeralForTest`. You just need to pass this arg in `additionalMongodArguments` in `MongoDbRunner.Start()`

**Comment by JohannesHoppe** [comment]
But it's still only available in MongoDB Enterprise, isn't it?

**Comment by 3nuc** [comment]
@JohannesHoppe 
https://docs.mongodb.com/manual/release-notes/3.2/#ephemeralfortest-storage-engine
https://www.thomasb.fr/2017/12/unit-testing-mongodb-queries/
>MongoDB has an “inMemory” storage engine, but it’s reserved to the (paid) Enterprise edition. Fortunately, since 3.2, even the Community edition has a not-very-well-documented “ephemeralForTests” storage engine, which loads up an in-memory Mongo instance, and does not store anything on the hard drive (but has poor performances). Exactly what we need!

**Comment by JohannesHoppe** [comment]
@sethidden I don't think that we should change the default configuration. Every time we change one aspect, it breaks somewhere! 😅 

But what about a little bit more documentation in the `README.md`. You could show the advantages and disadvantages and how to set it up. I'm happy to merge a PR like that!
