### ISSUE TITLE
Could not find Mongo binaries using the search pattern of "tools\mongodb-win32*\bin".

### ISSUE THREAD

**Issue by AskKol** [Mongo2Go/Mongo2Go#39]
Hi, I was wondering if anyone has encountered a similar issue when using 'mongo2Go' on 'TeamCity'. It works absolutely brilliantly on my local machine, but, once I push my test to the server hosted locally by us i.e. the company I work for, it gives the above error during build. Any suggestion(s) would be appreciated. 
-Thanks in advance.

**Comment by Johlandabee** [comment]
Hi, could you provide a little more information?
- What version of Mongo2Go do you use?
- What is your framework version? Are you using Dotnet Core?
- How is your TeamCity task configured? Build Step? Are you using the MSBuild runner?

My best bet is that your TeamCity build uses a different output directory. Mongo2Go uses its assembly location as a base for a recursive folder search with a maximum depth of 6. Downwards and upwards.

**Comment by UnderHeavyDevelopment** [comment]
I have the same situation with **NCrunch** on local machine. 100% reproducibility.

Details:
NCrunch v3.9.0.1

```
  <package id="Mongo2Go" version="2.1.0" targetFramework="net461" />
  <package id="MongoDB.Bson" version="2.4.3" targetFramework="net461" />
  <package id="MongoDB.Driver" version="2.4.3" targetFramework="net461" />
  <package id="MongoDB.Driver.Core" version="2.4.3" targetFramework="net461" />
```

**Error**
```
Mongo2Go.MonogDbBinariesNotFoundException : Could not find Mongo binaries using the search pattern of "tools\mongodb-win32*\bin". We walked up the directories 6 levels from C:\Users\<user>\AppData\Local\NCrunch\10860\50\_ncrunchreferences and packages\Mongo2Go*\tools\mongodb-win32*\bin.  You can override the search pattern when calling MongoDbRunner.Start.  We have detected the OS as Win32NT
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
   at Mongo2Go.Helper.MongoBinaryLocator.ResolveBinariesDirectory() in X:\Mongo2Go\src\Mongo2Go\Helper\MongoBinaryLocator.cs:line 59
   at Mongo2Go.Helper.MongoBinaryLocator.get_Directory() in X:\Mongo2Go\src\Mongo2Go\Helper\MongoBinaryLocator.cs:line 43
   at Mongo2Go.MongoDbRunner..ctor(IPortPool portPool, IFileSystem fileSystem, IMongoDbProcessStarter processStarter, IMongoBinaryLocator mongoBin, String dataDirectory) in X:\Mongo2Go\src\Mongo2Go\MongoDbRunner.cs:line 127
   at Mongo2Go.MongoDbRunner.Start(String dataDirectory, String searchPatternOverride) in X:\Mongo2Go\src\Mongo2Go\MongoDbRunner.cs:line 36
```

In root\packages\Mongo2Go.2.1.0\tools\mongodb-win32-x86_64-2008plus-3.2.7\bin I do have:
- mongod.exe
- mongoexport.exe
- montoimport.exe

My test project is in: root\TestProject

**Comment by Johlandabee** [comment]
The problem is that NCrunch seems to ouput asseblies at `C:\Users\<user>\AppData\Local\NCrunch\10860\50\_ncrunchreferences` but your MongoDB binaries are located at `root\packages\Mongo2Go.2.1.0\tools\mongodb-win32-x86_64-2008plus-3.2.7\bin`. That exceeds the current **max recursion depth of 6**.

The bit of code in charge causing this behavior is the following method, located at [FolderSearch.cs](https://github.com/Mongo2Go/Mongo2Go/blob/master/src/Mongo2Go/Helper/FolderSearch.cs):
````csharp
public static string CurrentExecutingDirectory()
{
    string filePath = new Uri(typeof(FolderSearch).GetTypeInfo().Assembly.CodeBase).LocalPath;
    return Path.GetDirectoryName(filePath);
}
````

**Comment by koraybalci** [comment]
As a workaround, I changed **Include static references in workspace** setting to *False* in NCrunch manually and my tests seem to pass for now.

![image](https://user-images.githubusercontent.com/1880390/29203121-9fdb3f9a-7eb1-11e7-96ef-c7b6267922df.png)

**Comment by JohannesHoppe** [comment]
👍

**Comment by JohannesHoppe** [comment]
Is this a a problem with __the max recursion depth of 6__ or do we have two completely different folders. If it's just about the level of recursion
```
public const int MaxLevelOfRecursion = 6;
```
than we could easily increase the number?!

**Comment by VadimGatsura** [comment]
I faced with the same issue. I believe the main cause of issue is searching of folder with mongo binaries relatively current execution folder.
I use Mongo2Go with .Net Framework 4.6.1.  I replaced packages.config file by PackageReferences in csproj file, because TeamCity doesn't restore System.Runtime assembly with packages.config during build. By this reason Mongo2Go NuGet package is downloaded to global nuget cache (by default it is %userprofile%\.nuget\packages\mongo2go), but build folder has level of recursion more than 6 relatively nuget global cache.
I believe that adding base directory parameter to MongoDbRunner.Start method can resolve the issue, at least in my case.
If you agree with this, I can create pull request.

**Comment by JohannesHoppe** [comment]
>  I replaced packages.config file by PackageReferences in csproj file, because TeamCity doesn't restore System.Runtime assembly with packages.config during build

Strange.. ` packages.config` --> We have done this for ages! 

Option A)
Run an old-style build. Or use nuget.exe directly.

Option B)
Pull request is welcome, if it does not introduce a breaking change.

**Comment by culaja** [comment]
`public const int MaxLevelOfRecursion = 6;`

In one of my solutions I have solution folder structure more than 6 levels depth, so in my opinion this parameter should be made configurable.
Another option is to remove this parameter and to end recursion when startPath in FindFolderUpwards is null (this code is already present).

**Comment by culaja** [comment]
@JohannesHoppe Do you plan to increase this number? As mentioned above I have directory depth more than 6 levels, but I think some general solution (like removing this configurable item) would be better.

**Comment by JohannesHoppe** [comment]
> Another option is to remove this parameter and to end recursion when startPath in FindFolderUpwards is null (this code is already present).

I'm open for that change. If you send such a PR, then I will merge it.

**Comment by culaja** [comment]
I've created the PR. All tests pass (I haven't added any new tests).

**Comment by JohannesHoppe** [comment]
see #50

**Comment by JohannesHoppe** [comment]
Thanks for the PR. Runs flawlessly on windows (only, still broken on Linux see #47)
I will publish v2.2.3 soon.

**Comment by nickmkk** [comment]
Is this supposed to be fixed?  I'm still getting this error with v2.2.6 in projects that use PackageReference nuget packages.  In my case the actual binaries are here `C:\Users\nickm\.nuget\packages\mongo2go\2.2.6\tools\mongodb-win32-x86_64-2008plus-ssl-3.6.1\bin`.

```
Mongo2Go.MonogDbBinariesNotFoundException
Could not find Mongo binaries using the search pattern of "tools\mongodb-win32*\bin". We walked up to root directory from C:\Projects\AppRiver\AppRiver.Office365.PartnerTools\AppRiver.Office365.PartnerTools.Tests\bin\Debug and packages\Mongo2Go*\tools\mongodb-win32*\bin.  You can override the search pattern when calling MongoDbRunner.Start.  We have detected the OS as Microsoft Windows 10.0.17134 
   at Mongo2Go.Helper.MongoBinaryLocator.ResolveBinariesDirectory()
   at Mongo2Go.Helper.MongoBinaryLocator.get_Directory()
   at Mongo2Go.MongoDbRunner..ctor(IPortPool portPool, IFileSystem fileSystem, IMongoDbProcessStarter processStarter, IMongoBinaryLocator mongoBin, String dataDirectory)
   at Mongo2Go.MongoDbRunner.Start(String dataDirectory, String searchPatternOverride)
```

**Comment by culaja** [comment]
@nickmkk Are you still having the same problem? Are you sure that Mongo binaries are present in the nuget directory?

**Comment by JohannesHoppe** [comment]
@nickmkk Sounds like you found the reason and a solution. Could you make a patch that looks in both locations? I'm looking forward to a PR! 👍

**Comment by JohannesHoppe** [comment]
That's fine, too. Follow up issue is here: #55 
PRs welcome!
