### ISSUE TITLE
Add binaries for MongoDB 3.6 or above

### ISSUE THREAD

**Issue by joehmchan** [Mongo2Go/Mongo2Go#45]
It would be great to run MongoDB 3.6.x. Looks like .NET Driver 2.5 supports MongoDB 3.6.

**Comment by iberodev** [comment]
any update on this? I am using MongoDB.Driver 2.6.1 and I cannot use mongo2Go for the mongoDb version v3.6.4

**Comment by iberodev** [comment]
Is this project still ongoing?

**Comment by JohannesHoppe** [comment]
Many thanks for pushing me a bit, Mongo2Go was updated to MongoDB 3.6.1: 
https://www.nuget.org/packages/Mongo2Go/2.2.2

The project is still alive, as soon as people continue to submit PRs (#46)! 😄
