### ISSUE TITLE
Mongo2Go sometimes not able to pick up data in collection

### ISSUE THREAD

**Issue by smukherjee-rythmos** [Mongo2Go/Mongo2Go#48]
Using Mongo2Go for mocking the mongo db calls. Below would be the structure am, using. Environment: .Net Core 2.0 / VS 2017

Helper.cs -> Creates the the Mongo2Go runner instance the returns the same (Non single-ton)

In any test class I am getting the runner instance like `new Helper<T>().GetRunnerinstance()` and using the same instance for all test cases/methods. below would a small sample code as how using Mongo2Go

            this.mockRepository.Setup(x => x.AddDocumentAsync(It.IsAny<ABC>()))
                                  .Callback(() => this.Helper.Collection.InsertOneAsync(abc))
                                  .Returns(Task.FromResult<ABC>(abc));

in above piece of code, am using MOQ and calling a local Mongo2Go call instead of actual repository call. Then to verify or assert am trying to get the same inserted local data like 

            var data = await this.Helper.Collection.Find(new BsonDocument(nameof(ABC.Name), Constants.Name)).ToListAsync();
            var actual = data.Single(); // this line behaves wired

When I run all the test cases either from VS or through command prompt `dotnet test` the code line `data.Single()` fails with exception ... *empty collection, no elements*. The reason is obvious that the mongo `Find()` call didn't fetch any result through it should have since I have just inserted the same record.

Very strange thing is that, it runs absolutely fine when I debug the test but fails when just run only that test or all test discovered.

Any idea, why is it behaving so? Please help

**Comment by ash23** [comment]
I can confirm this seems to be related to the target framework (netcoreapp2.0 vs net461) rather than the OS under which Mongo2Go is used.
I.e., also when targeting netcoreapp2.0 under Windows Mongo2Go seems to cause the program to freeze (as soon as the program attempts to access MongoDB via the c# driver). Also the mongod process (launched by Mongo2Go) becomes inaccessible, i.e you cannot even connect to the database using other tools such as NoSql Manager for MongoDB. As soon as the c# application is killed the mongod process again is accessible using other tools.

However when targeting net461 under Windows everything works fine without any problems.

**Comment by smukherjee-rythmos** [comment]
Comment from Johan <notifications@github.com>

> I can confirm this seems to be related to the target framework (netcoreapp2.0 vs net461) rather than the OS under which Mongo2Go is used.
> I.e., also when targeting netcoreapp2.0 under Windows Mongo2Go seems to cause the program to freeze (as soon as the program attempts to access MongoDB via the c# driver). Also the mongod process (launched by Mongo2Go) becomes inaccessible, i.e you cannot even connect to the database using other tools such as NoSql Manager for MongoDB. As soon as the c# application is killed the mongod process again is accessible using other tools.
> However when targeting net461 under Windows everything works fine without any problems.

See screen pic
![screenshot_1](https://user-images.githubusercontent.com/34125253/40769185-f60cdfcc-64d4-11e8-8e35-3996130b6e5b.png)

**Comment by chrisseroka** [comment]
Why is it closed? I'm still having the same issue on netcoreapp2.0
