### ISSUE TITLE
Mongo2Go.MonogDbBinariesNotFoundException v2

### ISSUE THREAD

**Issue by JohannesHoppe** [Mongo2Go/Mongo2Go#55]
@nickmkk commented [here](https://github.com/Mongo2Go/Mongo2Go/issues/39#issuecomment-408210947) regarding isse #39

-------

Is this supposed to be fixed?  I'm still getting this error with v2.2.6 in projects that use PackageReference nuget packages.  In my case the actual binaries are here `C:\Users\nickm\.nuget\packages\mongo2go\2.2.6\tools\mongodb-win32-x86_64-2008plus-ssl-3.6.1\bin` since the PackageReference option just uses packages from the global cache.

```
Mongo2Go.MonogDbBinariesNotFoundException
Could not find Mongo binaries using the search pattern of "tools\mongodb-win32*\bin". We walked up to root directory from C:\...\bin\Debug and packages\Mongo2Go*\tools\mongodb-win32*\bin.  You can override the search pattern when calling MongoDbRunner.Start.  We have detected the OS as Microsoft Windows 10.0.17134 
   at Mongo2Go.Helper.MongoBinaryLocator.ResolveBinariesDirectory()
   at Mongo2Go.Helper.MongoBinaryLocator.get_Directory()
   at Mongo2Go.MongoDbRunner..ctor(IPortPool portPool, IFileSystem fileSystem, IMongoDbProcessStarter processStarter, IMongoBinaryLocator mongoBin, String dataDirectory)
   at Mongo2Go.MongoDbRunner.Start(String dataDirectory, String searchPatternOverride)
```

I think "ResolveBinariesDirectory" should look for the binaries in the current users global cache if they are not found.  It would solve this issue for people who use PackageReference(which is the nuget standard going forward).

**Comment by JohannesHoppe** [comment]
@nickmkk Sounds like you found the reason and a solution. Could you make a patch that looks in both locations? I'm looking forward to a PR! 👍

**Comment by nickmkk** [comment]
PR submitted https://github.com/Mongo2Go/Mongo2Go/pull/56
