### ISSUE TITLE
Error parsing command line: unrecognised option '--sslMode'

### ISSUE THREAD

**Issue by chrisseroka** [Mongo2Go/Mongo2Go#59]
While running `MongoDbRunner.Start()` I get the following error:
`Error parsing command line: unrecognised option '--sslMode'`

It happened after updating Mongo2Go to newer version. The latest working version is `2.2.1`
OS: Windows 10

**Comment by JohannesHoppe** [comment]
I can't reproduce this. Do you have more infos?

**Comment by JohannesHoppe** [comment]
No answer. Closing this.
