### ISSUE TITLE
System.ObjectDisposedException : Cannot access a disposed object while running test

### ISSUE THREAD

**Issue by pseudoramble** [Mongo2Go/Mongo2Go#67]
**Setup for this issue:** OSX, dotnet core 2.2, Mongo2Go latest version, NUnit.

First thing, thanks for the work on this! Nice little project you have here and I appreciate having this as an option.

I have a method I'm testing that looks like this:

```
public async Task<Thing> FindAsync(string id)
{
  var mongoCollection = this.getMongoCollection();
  var results = await mongoCollection.FindAsync(
    thing => thing.Id == id
  );

  if (results.Any())
  {
    return results.First();
  }

  return null;
}
```

I start up Mongo2Go with NUnit so that it will only be configured once at the beginning of running the test suite and then holding onto references to each of these during the execution of each test:

```
  private MongoDbRunner _runner;
  private MongoClient _client;
  private IMongoDatabase _fakeDb;

  [OneTimeSetUp]
  public void Init()
  {
    _runner = MongoDbRunner.Start();
    _client = new MongoClient(_runner.ConnectionString);
    _fakeDb = _client.GetDatabase("ThingiesIntegrationTest");

    var sampleThing = new Thing();
    sampleThing.Id = "abc123";
    _fakeDb.GetCollection<Thing>("Thingies")
      .InsertOne(sampleThing);

    var test = _fakeDb.GetCollection<FileSummary>("Thingies")
      .Find(f => f.Id == sampleFileSummary.Id);
  }
```

The test itself that's exercising the conditional in the code is:

```
  [Test]
  public async Task FindAsync_Locates_Thing()
  {
    var realThingId = "abc123";
    var thing = await Repository.FindAsync(realThingId);
      
    Assert.That(
      thing.Id, Is.EqualTo(realThingId), "Thing ID's do not match");
  }
```

When I execute the tests in this setup, I get the following exception:

```
System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'AsyncCursor`1'.
Stack Trace:
   at MongoDB.Driver.Core.Operations.AsyncCursor`1.ThrowIfDisposed()
   at MongoDB.Driver.Core.Operations.AsyncCursor`1.MoveNext(CancellationToken cancellationToken)
   at MongoDB.Driver.IAsyncCursorExtensions.GetFirstBatch[TDocument](IAsyncCursor`1 cursor, CancellationToken cancellationToken)
   at MongoDB.Driver.IAsyncCursorExtensions.First[TDocument](IAsyncCursor`1 cursor, CancellationToken cancellationToken)
   at Thingies.Repositories.ThingieRepository.FindAsync(String id) in /Users/asdf/Code/project/Repositories/ThingieRepository.cs:line 38
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)
```

I'm not exactly sure why the cursor is being disposed of after invoking `Any()` on it. If I omit that line and re-run this test, it passes as expected. I can also work around this issue by changing to `AsyncCursor.FirstOrDefault()` for my scenario, but I'd like to know what I'm doing wrong.

I'm glad to dig in and provide more detailed information (or even a PR if it comes to it). I  need a pointer on what information I should get and where to begin looking at things. Or if I am just using this wrong, I'll correct that mistake myself.

**Comment by pseudoramble** [comment]
After looking it over some more, I believe it was my fault for misunderstanding how to use `AsyncCursor` properly. It will only allow enumerating the cursor one time. I had assumed that `Any()` would not consume the cursor, but it appears that it does. So to avoid this issue, copying it into a new collection is the way I figured out on how to work with it.

Sorry for the noise. Thanks.

**Comment by JohannesHoppe** [comment]
@pseudoramble Thank you for the answer. It will definitely help the next person searching!

**Comment by boatright3151** [comment]
@pseudoramble Thanks very much . this post really helped me.
