### ISSUE TITLE
Custom arguments to the running MongoDb instance?

### ISSUE THREAD

**Issue by zmira** [Mongo2Go/Mongo2Go#68]
Hi.
Is it possible to have custom arguments passed to the running MongoDb instance?
For example, `quiet` (https://docs.mongodb.com/manual/reference/parameters/#param.quiet) or `systemLog.quiet` (https://docs.mongodb.com/manual/reference/configuration-options/#systemLog.quiet).

I have see that the MongoDb arguments are defined in `MongoDbProcessStarter.cs` and don't allow custom arguments. Is there any other way?

Thanks.

**Comment by JohannesHoppe** [comment]
This is not implemented. You could make a PR for that.

**Comment by zmira** [comment]
PR created: https://github.com/Mongo2Go/Mongo2Go/pull/69

**Comment by broder-peters-k24** [comment]
@JohannesHoppe would love to have this!
Thanks @zmira for making changes!

@JohannesHoppe will this topic come soon? According to the PR you need some time?

**Comment by JohannesHoppe** [comment]
Thanks for the patience, v2.2.10 is right now building/deploying on AppVeyor.
