### ISSUE TITLE
Option to set the default port for StartForDebugging()

### ISSUE THREAD

**Issue by dannyBies** [Mongo2Go/Mongo2Go#71]
I would like to be able to set a port when running StartForDebugging() as the current default port (27017) may be in use on my local machine which in turn causes my integration tests to fail.

I thought of two options on how to implement this, I'd be happy to create a PR if this is something that you want to add to Mongo2Go.

* Add an optional parameter port which defaults to MongoDbDefaults.DefaultPort
* Add an optional parameter searchForAvailablePort which defaults to false. When set to true it will use portPool.GetNextOpenPort() to find the next available open port.

**Comment by dannyBies** [comment]
Hi @JohannesHoppe , have you had a chance to look at this? This feature would help my team a lot!

**Comment by JohannesHoppe** [comment]
Thanks for the patience, v2.2.10 is right now building/deploying on AppVeyor.
