### ISSUE TITLE
MongoDbRunner.Start() not work correctly in vs 2017 test tool with xunit project

### ISSUE THREAD

**Issue by jingliancui** [Mongo2Go/Mongo2Go#76]
`MongoDbRunner.Start()` not work in vs 2017 test tool with xunit project in `run test operation` and `debug test operatioin`
`MongoDbRunner.StartForDebugging()` is done with  `run test operation` and `debug test operatioin` in vs 2017 test tool with xunit project.

`MongoDbRunner.Start()`  and `MongoDbRunner.StartForDebugging()`  all correct in `dotnet test` command line tool

**Comment by JohannesHoppe** [comment]
This is not enough information to fix the problem. Please provide a sample project so that someone can take a look at it.

**Comment by jingliancui** [comment]
Got it ,i will upload sample code asap

**Comment by jingliancui** [comment]
[MongoSample.zip](https://github.com/Mongo2Go/Mongo2Go/files/3169095/MongoSample.zip)
Hi @JohannesHoppe  , Sample was uploaded,
And now I know the problem aim at `MongoDbRunner.Start();`
You can show issue again by these steps:
Restart your pc(or kill the mongod.exe at task manager) , this step let the mongod.exe not start at pc's start up.
Then run `dotnet test` command for the project (or run(debug) test use visual studio)
Then after about 30 second , test pass failed.(about 30 seconds because method  `MongoDbRunner.Start();` not start the mongod.exe).

If you change code to use `MongoDbRunner.StartForDebugging();` 
Test will be pass in about 15 seconds.
Then if you change code to  `MongoDbRunner.Start();`  and it'll be pass.(because mongod.exe had started)

**Comment by jingliancui** [comment]
Oh , Today I check the document you provide port of `MongoDbRunner.Start();` is 27018, I write hard code port to 27017 in my code. So that your document is right. : )

**Comment by JohannesHoppe** [comment]
😉👍
