### ISSUE TITLE
UP FOR GRAPS: Download latest Mongodb binaries automatically for Linux / OSX / Win

### ISSUE THREAD

**Issue by JohannesHoppe** [Mongo2Go/Mongo2Go#82]
Dear friends,

as you might know, I'm not very active in the .NET world anymore and don't have resources to develop new features as well. At the same time I also know that there is a certain user base that depends on new versions of Mongo2Go and the included MongoDB binaries.

I continuously get pull requests with executable code (eg #77 which is still open). This is great and I could merge it, BUT then there would be the danger that malicious code would be added to the Nuget package. I won't take this risk and therefore I download all executable files myself again to see if the files are absolutely binary equal to the PR. This is frustrating.

So I would like to ask __YOU__ to develop a solution.
This solution might execute the following steps:

1. clear the folder in https://github.com/Mongo2Go/Mongo2Go/tree/master/tools
2. download and unzip the packages from http://downloads.mongodb.org/
3. moves only the necessary files to the correct folder
4. optional: updates README 👍
5. optional: anything which looks a little bit like automatisation 👍👍

Batch file, PowerShell, C# program I don't care, as long as it does its job. Personally, I'm a big fan of PowerShell Core, but hey, I'm not the one who can make demands here.

Cheers,
Johannes

FYI @sherry-ummen @zmira @nachiappannk @jbogard

**Comment by jbogard** [comment]
Should this also pin the correct MongoDB client version with the server?

**Comment by JohannesHoppe** [comment]
Sounds reasonable!

**Comment by fjmorel** [comment]
Which OS should this script try to support?

1. It looks like 4.2 dropped Windows 2008 and raised the requirement to 2012. Is that ok? https://www.mongodb.org/dl/win32/
2. I don't see 4.2.x on this page https://www.mongodb.org/dl/osx/ but it is listed on the general download page. I tried https://www.mongodb.org/dl/macos with no luck. Planning on reporting this to them.
3. There are lots of linux versions. Which one is currently included? Should we try to expand to support different versions?

![image](https://user-images.githubusercontent.com/1383382/82955093-12e54d80-9f7c-11ea-909e-d7365b88ceb6.png)

Once done for 4.2, it should be fairly simple to later make PRs that fix the links to use 4.4, 4.6, etc.

**Comment by JohannesHoppe** [comment]
Hi, thanks for stepping in! 😃 

Dropping older versions of Windows is fine for me.
You probably have already seen this [README](https://github.com/Mongo2Go/Mongo2Go/blob/master/tools/README.md).

So, in the past I have just manually downloaded the latest files from
* https://www.mongodb.org/dl/linux/x86_64
* https://www.mongodb.org/dl/osx
* https://www.mongodb.org/dl/win32/x86_64-2008plus-ssl

Honestly I have no clue which derivates are supported by `linux/x86_64`. But it runs on Travis-CI which is an Ubuntu Trusty. Until now nobody complained about support for an other linux derivative (and I am on a Mac, only).

**Comment by 0xced** [comment]
I'm working on a (C#) tool to automate the download of the latest version of MongoDB. I will open a pull request soon.

**Comment by JohannesHoppe** [comment]
👍👍👍👍

**Comment by 0xced** [comment]
Have you had a chance to look at it?

**Comment by JohannesHoppe** [comment]
@0xced Thank you very much for your great work, I watch the development on your PR and I'm super happy that you contributing here. 😃 👍👍 

But I'm sorry, that I can't participate at any open source project right now (including reviewing PRs and publishing a new version) . I am dealing with a death from a nearest relative right now. Next week I will start again to work on my computer.

**Comment by 0xced** [comment]
My sincere condolences, Johannes. Open source work will wait, take care of yourself and your relatives.
