### ISSUE TITLE
Chooses wrong version of mongo binaries when multiple versions are installed

### ISSUE THREAD

**Issue by mihevc** [Mongo2Go/Mongo2Go#86]
I have 2.2.9 installed and 2.2.12.  It pulls the binaries from 2.2.9 and tries to use an SSL flag that is invalid. 

I have a fix for this and a test that covers it but I can't push a feature branch in order to create a pull request.  Let me know how you would like to proceed.

**Comment by JohannesHoppe** [comment]
You should fork the repo, do your changes and send a PR. 🙂

**Comment by mihevc** [comment]
OK, I did that. Thanks for the info.

**Comment by JohannesHoppe** [comment]
New version released. Please try out Mongo2Go 2.2.13.
