### ISSUE TITLE
Problem running test in a linux environment

### ISSUE THREAD

**Issue by smendez-zenfolio** [Mongo2Go/Mongo2Go#88]
I have a problem running my tests in my TEST environment (Linux), when I run it locally everything works perfect (WIN10 Computer) . I tried to instance the Mongo runner like this:

`_runner = MongoDbRunner.Start(
                binariesSearchPatternOverride: "tools/mongodb-linux*/bin",
                binariesSearchDirectory: "/root/.nuget/packages/mongo2go/2.2.12",
                singleNodeReplSet: true);`

But I still got an error that tjere is no such file or directory, the weirdest thing is the error is a win32exception but my environment is linux

> 12:34:44  [91m[xUnit.net 00:00:12.45]     Project.SiteViewer.IntegrationTests.Services.EventHandlerServiceShould.SitePublishedHandleAsync [FAIL]
12:34:44  [0m[91m[xUnit.net 00:00:12.48]     Project.SiteViewer.IntegrationTests.Controllers.SiteControllerShould.ShouldGetSiteByDomain [FAIL]
12:34:44  [0mFailed   Project.SiteViewer.IntegrationTests.Services.EventHandlerServiceShould.SitePublishedHandleAsync
12:34:44  Error Message:
12:34:44   System.ComponentModel.Win32Exception : No such file or directory
12:34:44  Stack Trace:
12:34:44     at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
12:34:44     at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
12:34:44     at System.Diagnostics.Process.Start()
12:34:44     at Mongo2Go.Helper.ProcessControl.StartAndWaitForReady(Process process, Int32 timeoutInSeconds, String processReadyIdentifier, String windowTitle) in W:\johanneshoppe\Mongo2Go\src\Mongo2Go\Helper\ProcessControl.cs:line 88
12:34:44     at Mongo2Go.Helper.MongoDbProcessStarter.Start(String binariesDirectory, String dataDirectory, Int32 port, Boolean doNotKill, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout) in W:\johanneshoppe\Mongo2Go\src\Mongo2Go\Helper\MongoDbProcessStarter.cs:line 44
12:34:44     at Mongo2Go.Helper.MongoDbProcessStarter.Start(String binariesDirectory, String dataDirectory, Int32 port, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout) in W:\johanneshoppe\Mongo2Go\src\Mongo2Go\Helper\MongoDbProcessStarter.cs:line 22
12:34:44     at Mongo2Go.MongoDbRunner..ctor(IPortPool portPool, IFileSystem fileSystem, IMongoDbProcessStarter processStarter, IMongoBinaryLocator mongoBin, String dataDirectory, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout) in W:\johanneshoppe\Mongo2Go\src\Mongo2Go\MongoDbRunner.cs:line 198
12:34:44     at Mongo2Go.MongoDbRunner.Start(String dataDirectory, String binariesSearchPatternOverride, String binariesSearchDirectory, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout) in W:\johanneshoppe\Mongo2Go\src\Mongo2Go\MongoDbRunner.cs:line 43
12:34:44     at Project.SiteViewer.IntegrationTests.Services.ServiceShouldBase`1..ctor(AutofacFixture autofacFixture) in /src/Project.SiteViewer/tests/Project.SiteViewer.IntegrationTests/Services/ServiceShouldBase`1.cs:line 26

Any ideas or possible solutions?

**Comment by scottmcarthur** [comment]
+1 me too. I am on the latest version of Mongo2Go. It all works great on my Mac in development. But I am running into this same exception when trying to deploy it in a linux docker container. Such a pain. @smendez-zenfolio  I am going to keep trying, did you ever get it working?

**Comment by mzaferyahsi** [comment]
I think I have the same issue when running the tests on GitHub Actions with latest ubuntu but it works perfectly on macos.

**Comment by Vertigo093i** [comment]
Which distro did you try?
It appears `mongod` has unmet dependencies (at least Alpine Linux lacks `libresolv.so.2`; others might have them not installed by default).
Run `ldd /root/.nuget/packages/mongo2go/2.2.12/tools/mongodb-linux-x86_64-4.0.2/bin/mongod` right after `dotnet restore` to see what they are.
I've successfully run `dotnet test` under **Debian GNU/Linux 10 (buster)** distro (`mcr.microsoft.com/dotnet/core/sdk:3.1-buster`) without any additional actions (while `-alpine` variant fails - see above).

**Comment by JohannesHoppe** [comment]
I usually only use Ubuntu or Debian, I don't have enough expertise when it comes to other distributions.

@smendez-zenfolio Please report your distro and the output of the `ldd`. Otherwise I will close this until new information are provided.
