### ISSUE TITLE
Transactions not working

### ISSUE THREAD

**Issue by aline-almeida** [Mongo2Go/Mongo2Go#89]
Hi!
I don't think issue #79 is fixed.
I've created a small sample based on @jbogard 's comment and ensured that collections were created before starting the transaction. It doesn't work.

I thought this would have to do with this statement referred in docs:
> Replica set initialization requires the use of a short delay to allow for the replica set to stabilize

But, as you can see in the sample, I've set singleNodeReplSetWaitTimeout to max value and still can't get it to work.

[MongoDbTransactionTests.zip](https://github.com/Mongo2Go/Mongo2Go/files/4104334/MongoDbTransactionTests.zip)

**Comment by panupetteri** [comment]
+1, we also have this issue and ensuring that the collections were created before starting the transaction did not fix the issue.

**Comment by AndreasTruetschel** [comment]
I ran into the exact same issue. I experimented a bit with the test project where this does not seem to occur. The case this works there is that a collection is first created and dropped! before the call to `session.StartTransaction()`.  

If a add a dummy collection and drop this right away

```csharp
_databaseRunner = MongoDbRunner.Start(singleNodeReplSet: true);
_databaseClient = new MongoClient(_databaseRunner.ConnectionString);
var wrappedDatabase = _databaseClient.GetDatabase(SGuid.NewGuid().ToString());
_ = wrappedDatabase.GetCollection<DummyEntry>("__dummy");
wrappedDatabase.DropCollection("__dummy");
```

with a simple dummy type

```csharp
private sealed class DummyEntry
{
    public int Id { get; set; }
}
```

to my test code, everything works as expected.

**Comment by javadparvaresh** [comment]
> ```cs
> DropCollection
> ```

tried this but it didn't work for 

```csharp
var runner = MongoDbRunner.Start(singleNodeReplSet: true);

var client = new MongoClient(runner.ConnectionString);
var database = client.GetDatabase(Guid.NewGuid().ToString());
database.CreateCollection("__dummy");
database.GetCollection<DummyEntity>("__dummy");
database.DropCollection("__dummy");

var session = client.StartSession();
session.StartTransaction();
session.AbortTransaction();
```
yet getting the same exception:
```
System.NotSupportedException : StartTransaction cannot determine if transactions are supported because there are no connected servers.
```

**Comment by AndreasTruetschel** [comment]
@javadparvaresh Some of my tests fail occasionally with this solution. I execute the create, get, drop collection workaround for 10 times in a loop. Then it works reproducibly.

**Comment by javadparvaresh** [comment]
@AndreasTruetschel by adding 10sec  Delay it fixed but makes test execution time so long... I think there will be a better way to check logs and detect that replica set is ready or not

**Comment by AndreasTruetschel** [comment]
Sure, I didn't intend this to be the general solution but just a (quick and dirty) workaround for all who, like me, are currently blocked on this.

**Comment by javadparvaresh** [comment]
I'm not proud of it, but the only way i make it work was to wring something like :
```csharp
private void ensureServerIsReady()
		{
			while (true)
			{
				try
				{
					var client = new MongoClient(this.runner.ConnectionString);
					var database = client.GetDatabase(Guid.NewGuid().ToString());
					database.CreateCollection("__dummy");
					database.GetCollection<DummyEntity>("__dummy");
					database.DropCollection("__dummy");

					var session = client.StartSession();
					session.StartTransaction();
					session.AbortTransaction();

					break;
				}
				catch
				{
					System.Threading.Thread.Sleep(2000);
				}
			}
		}
```

> Most of the time at first try it will pass, but I faced 3 times also on my tests

**Comment by AndreasTruetschel** [comment]
Thanks @javadparvaresh   
I build an extension method (also with an async version) for `IMongoClient` from our ideas. It can be found here:   
https://github.com/AI4E/AI4E/blob/6dbd38b6e36c921da100eea20dfb795094520f01/src/Storage/test/AI4E.Storage.MongoDB.Test/Utils/MongoClientExtension.cs  

This still is a workaround to unblock testing and other scenarios but NOT a general solution.

**Comment by realLiangshiwei** [comment]
Related https://github.com/Mongo2Go/Mongo2Go/issues/100

**Comment by JohannesHoppe** [comment]
New version released. Please try out Mongo2Go 2.2.13.
