### ISSUE TITLE
Feature: Disable (optional) console output

### ISSUE THREAD

**Issue by DR9885** [Mongo2Go/Mongo2Go#94]
It would be nice if we could just optionally disable all writes. Originally i was using --quiet, but it still logs too much.

**Comment by victortrusov** [comment]
`MongoDbRunner.Start(additionalMongodArguments: "--quiet --logpath /dev/null");` works on Linux/MacOS but in my case increases the test time

**Comment by JohannesHoppe** [comment]
see also #113
