### ISSUE TITLE
Argument --quiet not working on azure devops

### ISSUE THREAD

**Issue by regis-ranniere** [Mongo2Go/Mongo2Go#95]
I'm trying configured `MongoDbRunner` to not log messages using this configuration:

`MongoDbRunner.Start(additionalMongodArguments: "--quiet");`
But this didn't work... all log messages are showing on my log.

I'm using Mongo2Go with Xunit... 
Have any way to resolve this? Or what i'm doing wrong?

**Comment by willoftw** [comment]
Also having this issue running test from CLI and devops. Any way to hide this?

**Comment by victortrusov** [comment]
`MongoDbRunner.Start(additionalMongodArguments: "--quiet --logpath /dev/null");` works but in my case increases the test time

**Comment by JohannesHoppe** [comment]
Thanks for this tipp!

**Comment by JohannesHoppe** [comment]
related to #113
